List<Map<String, dynamic>> products = [
  {
    'id' : 1,
    'img': "assets/images/f1.png",
    'name' : 'Blueberry',
    'amount' : '\$32.4',
    'price' : '\$38',
    'offer' : '14%OFF',
    'kg' : '0.30kg',
  },
  {
    'id' : 2,
    'img': "assets/images/f2.png",
    'name' : 'Strawberry',
    'amount' : '\$19',
    'price' : '\$37',
    'offer' : '48%OFF',
    'kg' : '1.00NOS',
  },
  {
    'id' : 3,
    'img': "assets/images/f3.png",
    'name' : 'Pineapple',
    'amount' : '\$95',
    'price' : '\$119',
    'offer' : '',
    'kg' : '1.00NOS',
  },
  {
    'id' : 4,
    'img': "assets/images/f4.png",
    'name' : 'Apple',
    'amount' : '\$36',
    'price' : '\$41',
    'offer' : '28%OFF',
    'kg' : '0.50Kg',
  },
  {
    'id' : 5,
    'img': "assets/images/f5.png",
    'name' : 'Plum',
    'amount' : '\$85',
    'price' : '\$89',
    'offer' : '',
    'kg' : '1.00 Pack',
  },
  {
    'id' : 6,
    'img': "assets/images/f6.png",
    'name' : 'Raspberry',
    'amount' : '\$165',
    'price' : '\$488',
    'offer' : '',
    'kg' : '1.00 Box',
  },
  {
    'id' : 7,
    'img': "assets/images/f7.png",
    'name' : 'Orange',
    'amount' : '\$55',
    'price' : '\$75',
    'offer' : '27%OFF',
    'kg' : '1.00NOS',
  },
  {
    'id' : 8,
    'img': "assets/images/s1.png",
    'name' : 'Citrus',
    'amount' : '\$49',
    'price' : '\$68',
    'offer' : '28%OFF',
    'kg' : '1.00 Box',
  },
  {
    'id' : 9,
    'img': "assets/images/s2.png",
    'name' : 'Onion',
    'amount' : '\$130',
    'price' : '\$175',
    'offer' : '',
    'kg' : '1.00 Box',
  },
  {
    'id' : 10,
    'img': "assets/images/s3.png",
    'name' : 'Coconut',
    'amount' : '\$175',
    'price' : '\$199',
    'offer' : '',
    'kg' : '1.00 Nos',
  },
  {
    'id' : 11,
    'img': "assets/images/s4.png",
    'name' : 'Mustard Green',
    'amount' : '\$59',
    'price' : '\$69',
    'offer' : '14%OFF',
    'kg' : '1.00 Box',
  },
  {
    'id' : 12,
    'img': "assets/images/v.png",
    'name' : 'Tomato',
    'amount' : '\$89',
    'price' : '\$110',
    'offer' : '19%OFF',
    'kg' : '1.00 Box',
  },
  {
    'id' : 13,
    'img': "assets/images/v1.png",
    'name' : 'Cauliflower',
    'amount' : '\$19',
    'price' : '\$37',
    'offer' : '48%OFF',
    'kg' : '1.00 kg',
  },
  {
    'id' : 14,
    'img': "assets/images/v2.png",
    'name' : 'Broccoli',
    'amount' : '\$95',
    'price' : '\$119',
    'offer' : '',
    'kg' : '1.00 kg',
  },
  {
    'id' : 15,
    'img': "assets/images/v3.png",
    'name' : 'Cabbage',
    'amount' : '\$36',
    'price' : '\$41',
    'offer' : '28%OFF',
    'kg' : '1.00 Pack',
  },
  {
    'id' : 16,
    'img': "assets/images/v4.png",
    'name' : 'Galabrese Broccoli',
    'amount' : '\$85',
    'price' : '\$89',
    'offer' : '',
    'kg' : '1.00 Pack',
  },
  {
    'id' : 17,
    'img': "assets/images/v5.png",
    'name' : 'Carrot',
    'amount' : '\$165',
    'price' : '\$488',
    'offer' : '',
    'kg' : '1.00 Box',
  },
  {
    'id' : 18,
    'img': "assets/images/v6.png",
    'name' : 'Ladies Finger',
    'amount' : '\$175',
    'price' : '\$250',
    'offer' : '',
    'kg' : '1.00 Box',
  },
  {
    'id' : 19,
    'img': "assets/images/v7.png",
    'name' : 'Capsicum',
    'amount' : '\$62',
    'price' : '\$87',
    'offer' : '',
    'kg' : '1.00 Nos',
  },
  {
    'id' : 20,
    'img': "assets/images/v8.png",
    'name' : 'Potato',
    'amount' : '\$32.4',
    'price' : '\$38',
    'offer' : '14%OFF',
    'kg' : '0.30 Kg',
  },
];